version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fleetflow_db
      MYSQL_ROOT_PASSWORD: Samira12
    networks:
      - fleet-net
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fleetflow_db
    networks:
      - fleet-net

networks:
  fleet-net:
    driver: bridge

volumes:
  mysql_data: