spring.application.name=fleetflow-API
spring.datasource.url=jdbc:mysql://localhost:3307/fleetflow_db
spring.datasource.username:root
spring.datasource.password=Samira12

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
